In [1]:
import os
os.environ['TRANSFORMERS_OFFLINE'] = '1'
os.environ['HF_DATASETS_OFFLINE'] = '1'

In [2]:
import pandas as pd
from ITER_DBSCAN import ITER_DBSCAN
from evaluation import EvaluateDataset

2026-03-11 15:00:45.129030: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [3]:
filepath = "review_dengan_intent.csv"
df = pd.read_csv(filepath)
df.head(5)

,userName,score,content,at,intent
0,Nabila Livia,5,sukaa,2026-02-18 10:36:04,Praise & Gratitude
1,Antok Sumawan,5,ya bagus,2026-02-18 10:32:49,Praise & Gratitude
2,Khayyira Ira,5,aku suka banget sama tiktok ini,2026-02-18 10:32:45,Praise & Gratitude
3,Aksay Subang,1,akun gua entah kenapa di Ben padalah gua kaga ...,2026-02-18 10:31:33,Account Issue
4,kenzo zildane alvaro,1,tolong diperbaiki,2026-02-18 10:30:44,General Request/Complaint

In [4]:
%%time
model = ITER_DBSCAN(
    initial_distance= 0.3,
    initial_minimum_samples=30, 
    delta_distance=0.01, 
    delta_minimum_samples=1, 
    max_iteration=15,
    threshold= 1000,
    embedding_model= "IndoSBERT",
)

CPU times: user 14 μs, sys: 1 μs, total: 15 μs
Wall time: 19.8 μs

In [5]:
labels, evaluate_results = model.fit_predict_evaluate(filename=filepath, 
                                   filetype='csv', 
                                   text_column='content', 
                                   target_column='intent')

Loading Huggingface IndoSBERT model....
Model Loaded.

100%|██████████| 723/723 [02:29<00:00,  4.85it/s]

In [6]:
labels

[-1,
 0,
 2,
 3,
 -1,
 -1,
 1,
 -1,
 7,
 2,
 4,
 -1,
 1,
 5,
 -1,
 3,
 5,
 -1,
 -1,
 4,
 1,
 0,
 -1,
 1,
 -1,
 0,
 0,
 1,
 1,
 2,
 5,
 0,
 1,
 -1,
 1,
 0,
 4,
 8,
 -1,
 1,
 4,
 0,
 -1,
 -1,
 1,
 0,
 0,
 7,
 0,
 0,
 1,
 3,
 -1,
 1,
 -1,
 -1,
 5,
 -1,
 4,
 -1,
 7,
 1,
 -1,
 4,
 -1,
 1,
 0,
 -1,
 1,
 -1,
 1,
 -1,
 1,
 1,
 1,
 0,
 -1,
 1,
 0,
 0,
 1,
 0,
 -1,
 5,
 6,
 1,
 -1,
 8,
 1,
 1,
 -1,
 -1,
 6,
 -1,
 0,
 7,
 2,
 2,
 0,
 1,
 1,
 4,
 1,
 1,
 -1,
 -1,
 2,
 1,
 -1,
 5,
 1,
 -1,
 3,
 3,
 3,
 2,
 2,
 -1,
 0,
 -1,
 2,
 1,
 1,
 5,
 0,
 1,
 5,
 1,
 1,
 -1,
 2,
 -1,
 0,
 6,
 7,
 -1,
 1,
 1,
 -1,
 -1,
 2,
 -1,
 0,
 0,
 2,
 -1,
 1,
 -1,
 5,
 1,
 5,
 5,
 1,
 1,
 -1,
 1,
 -1,
 0,
 1,
 1,
 1,
 0,
 -1,
 -1,
 0,
 2,
 -1,
 -1,
 8,
 7,
 0,
 1,
 -1,
 2,
 0,
 -1,
 1,
 1,
 0,
 6,
 1,
 3,
 0,
 1,
 1,
 1,
 6,
 1,
 -1,
 7,
 0,
 5,
 -1,
 1,
 -1,
 0,
 -1,
 8,
 6,
 0,
 1,
 -1,
 1,
 -1,
 -1,
 0,
 0,
 5,
 5,
 1,
 1,
 3,
 0,
 -1,
 0,
 -1,
 3,
 -1,
 -1,
 5,
 1,
 -1,
 5,
 5,
 1,
 1,
 -1,
 1,
 0,
 -1,
 4,
 0,
 3,
 -1,
 1,
 5,
 -1,
 1,
 1,
 7,
 0,
 0,
 8,
 1,
 0,
 0,
 0,
 5,
 1,
 -1,
 0,
 -1,
 1,
 1,
 8,
 3,
 1,
 2,
 5,
 1,
 6,
 2,
 0,
 1,
 -1,
 -1,
 3,
 0,
 -1,
 -1,
 2,
 4,
 6,
 5,
 1,
 1,
 0,
 -1,
 -1,
 0,
 -1,
 1,
 -1,
 7,
 -1,
 -1,
 3,
 1,
 8,
 0,
 -1,
 1,
 1,
 -1,
 5,
 6,
 -1,
 -1,
 1,
 5,
 3,
 1,
 -1,
 1,
 4,
 1,
 -1,
 0,
 1,
 1,
 1,
 -1,
 -1,
 -1,
 0,
 -1,
 0,
 1,
 0,
 8,
 1,
 0,
 0,
 1,
 -1,
 2,
 3,
 4,
 3,
 0,
 5,
 -1,
 1,
 3,
 -1,
 3,
 -1,
 6,
 -1,
 1,
 0,
 1,
 -1,
 -1,
 0,
 -1,
 0,
 0,
 0,
 4,
 3,
 1,
 0,
 0,
 1,
 -1,
 2,
 0,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 6,
 1,
 0,
 -1,
 -1,
 -1,
 1,
 8,
 1,
 1,
 1,
 0,
 -1,
 5,
 -1,
 3,
 0,
 1,
 1,
 -1,
 0,
 -1,
 0,
 3,
 0,
 -1,
 0,
 1,
 1,
 1,
 -1,
 6,
 -1,
 8,
 1,
 -1,
 1,
 6,
 -1,
 7,
 1,
 -1,
 -1,
 1,
 1,
 2,
 -1,
 -1,
 7,
 1,
 1,
 -1,
 -1,
 -1,
 0,
 0,
 1,
 2,
 -1,
 3,
 -1,
 -1,
 4,
 0,
 0,
 -1,
 8,
 1,
 4,
 -1,
 3,
 2,
 8,
 3,
 5,
 0,
 -1,
 0,
 1,
 -1,
 1,
 0,
 1,
 3,
 0,
 0,
 2,
 1,
 0,
 1,
 4,
 1,
 1,
 0,
 1,
 -1,
 -1,
 2,
 -1,
 3,
 8,
 1,
 1,
 4,
 1,
 -1,
 -1,
 1,
 5,
 1,
 1,
 6,
 2,
 -1,
 1,
 1,
 1,
 2,
 1,
 1,
 5,
 4,
 0,
 1,
 1,
 2,
 1,
 0,
 1,
 0,
 1,
 5,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 0,
 1,
 -1,
 1,
 1,
 1,
 0,
 2,
 -1,
 1,
 -1,
 -1,
 3,
 1,
 -1,
 0,
 -1,
 5,
 4,
 4,
 -1,
 5,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 3,
 0,
 -1,
 2,
 4,
 1,
 3,
 2,
 1,
 -1,
 1,
 3,
 -1,
 3,
 7,
 -1,
 0,
 0,
 7,
 -1,
 -1,
 5,
 4,
 3,
 -1,
 -1,
 5,
 3,
 0,
 0,
 1,
 5,
 5,
 -1,
 -1,
 -1,
 0,
 2,
 -1,
 1,
 0,
 0,
 2,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 1,
 7,
 1,
 1,
 0,
 1,
 6,
 -1,
 1,
 -1,
 -1,
 8,
 7,
 -1,
 0,
 7,
 -1,
 0,
 5,
 1,
 1,
 -1,
 -1,
 -1,
 1,
 5,
 3,
 1,
 -1,
 0,
 8,
 -1,
 0,
 -1,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 -1,
 7,
 0,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 2,
 -1,
 -1,
 3,
 0,
 0,
 3,
 -1,
 -1,
 5,
 1,
 3,
 5,
 1,
 0,
 1,
 5,
 1,
 -1,
 -1,
 -1,
 5,
 -1,
 1,
 -1,
 3,
 1,
 5,
 1,
 -1,
 1,
 1,
 0,
 1,
 0,
 8,
 6,
 -1,
 6,
 -1,
 1,
 5,
 2,
 -1,
 -1,
 2,
 1,
 1,
 2,
 -1,
 1,
 5,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 2,
 5,
 5,
 6,
 1,
 -1,
 0,
 1,
 -1,
 1,
 2,
 3,
 -1,
 1,
 5,
 -1,
 5,
 4,
 1,
 7,
 1,
 -1,
 0,
 1,
 1,
 0,
 -1,
 -1,
 0,
 -1,
 -1,
 0,
 -1,
 0,
 1]

In [7]:
evaluate_results = pd.DataFrame.from_dict(evaluate_results)
evaluate_results

,initial_distance,initial_minimum_samples,delta_distance,delta_minimum_samples,max_iteration,threshold,features,embedding_model,metric,iteration,...,adjusted_mutual_info_score,adjusted_rand_score,silhouette_score,davies_bouldin,calinski_harabasz,accuracy,precision,recall,f1,intents
0,0.42,18,0.01,1,15,1000,None,<IndoSBERTEmbedding.IndoSBERTEmbedding object ...,precomputed,0,...,0.24,0.17,0.178,2.064,150.986,0.468880,36.3,46.9,38.2,2
1,0.43,17,0.01,1,15,1000,None,<IndoSBERTEmbedding.IndoSBERTEmbedding object ...,precomputed,0,...,0.24,0.17,0.178,2.064,150.986,0.468880,36.3,46.9,38.2,2
2,0.44,16,0.01,1,15,1000,None,<IndoSBERTEmbedding.IndoSBERTEmbedding object ...,precomputed,0,...,0.24,0.18,0.170,2.141,144.040,0.467497,35.3,46.7,37.9,2
3,0.45,15,0.01,1,15,1000,None,<IndoSBERTEmbedding.IndoSBERTEmbedding object ...,precomputed,0,...,0.24,0.18,0.170,2.141,144.040,0.467497,35.3,46.7,37.9,2