In [1]:
import pandas as pd
from ITER_DBSCAN import ITER_DBSCAN
from evaluation import EvaluateDataset

2026-02-19 14:36:32.300946: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [2]:
filepath = "review_dengan_intent.csv"
df = pd.read_csv(filepath)
df.head(5)

,userName,score,content,at,intent
0,Nabila Livia,5,sukaa,2026-02-18 10:36:04,Praise & Gratitude
1,Antok Sumawan,5,ya bagus,2026-02-18 10:32:49,Praise & Gratitude
2,Khayyira Ira,5,aku suka banget sama tiktok ini,2026-02-18 10:32:45,Praise & Gratitude
3,Aksay Subang,1,akun gua entah kenapa di Ben padalah gua kaga ...,2026-02-18 10:31:33,Account Issue
4,kenzo zildane alvaro,1,tolong diperbaiki,2026-02-18 10:30:44,General Request/Complaint

In [3]:
print('Before: ', len(df))
df = df.dropna()
print('After: ', len(df))
df = df.reset_index()
del df['index']
df.intent.value_counts()

Before:  1000
After:  1000

intent
Unlabeled/Noise              277
Praise & Gratitude           271
Account Issue                129
Performance Issue            100
Feature Complaint/Request     90
Technical Bug/Crash           72
General Request/Complaint     38
Monetization/Earning          23
Name: count, dtype: int64

In [4]:
dataset = df.content.values.tolist()

In [5]:
dataset

['sukaa',
 'ya bagus',
 'aku suka banget sama tiktok ini',
 'akun gua entah kenapa di Ben padalah gua kaga ngapa ngapain',
 'tolong diperbaiki',
 '😁',
 'cukup lumayan sih sama aplikasi ini , hanya saja banyak bug , kadang suka keluar sendiri dari aplikasi . terimakasih',
 'membagi inspirasi dan motivasi',
 'Sya kasi bintang 5 biyar lebih bagus lagi hai bosku kenpa titok ya sering elor terus adh aph dengan titok ya',
 'sangat bagus apk nya saya dapat uang juga dari tiktok',
 'mantap',
 'senang bgt',
 'aplikasi jelek',
 'bagus tapi akun ku di block...😭😭',
 'gaseru tiktok sampah saya gabisa join padahal tanggal lahir saya sudah benar',
 'Tiktok ini tidak ngeleg makanya saya download ini',
 'apk nya bagus saya suka, tapi diorang lain mempunyai potongan harga, sedang kan diakun saya ko tidak ada ya, tolong update kan akun saya agar mempunyai potongan harga.....terimakasih',
 'good',
 'tolong bug untuk postingan di atur ulang soalnya setiap muat postingan ngestag di 30% terus',
 'o aj sih😹',
 'tolong vidio seksual di larang sekarang banyak banget cwk bukak aurat',
 'nge-lag padahal jaring bagus terus kadang juga suka tiba tiba follow akun orang',
 'asikkkk',
 'suka ngelag buka komentar,ubah privasi atau yg lain lain kocak padahal wifi lancar',
 'bagus banget apk nyaa',
 'soalnya ngeleg',
 'lag terus sampe muak banget. kalo sekali masih wajar lah ini udh keberapa kali. buat ga nyaman nonton, bentar bentar lag ga enak. jadi ga terlalu pengen buka apknya lagi',
 'jelek',
 'masyarakat',
 'bagus',
 'bagusss sekaliii',
 'knpaa hp saya ngelek saat bukak live tiktok',
 'kenapa akhir akhir ini tiktok ga bisa di buat buka komentar dll, padahal di buat scrol lancar lancar aja',
 'tolong fitur repostnya di perbaiki min, sya buat akun baru tidak ada fitur repostnya',
 'mantap',
 'suka,menarik,pokok nya aku suka,tapi akun aku ke blokir ga tau karna apa ,dan aku BENCI ITUU!!!!!',
 'woi assuuuuuuuu nyapo book blok tiktok ku wes wes ilang Kabeh',
 'good',
 'sangat baguss',
 'kok gbs posting ulang?',
 'aplikasi nya lelet',
 'mohon maaf ini kenapa saya tidak bisa ngeklaim hadiah dari menjawab pertanyaan dari sebuah lokasi, tolong diperbaiki',
 'app nya bagus cuma suka diblokir tiba² sama tiktok nya jadi ya gabisa lagi',
 'apk bagus',
 'seru',
 'apk nya udah baguss bgttt tp tolong adain firur kembaliin draft plisss butuh bgttt🥲🥲🥲😭😭',
 'ngeleg gajelas',
 'mudah dipahami',
 'tik tok jahat banget masak aku gk bisa nonton,akun aku di blokir selamanya pula😓🙁 udh 4th di blokirr😔😔😔 aku pake tik tok lite juga gabisa padal tik tok seru lohh tapi knp kok punya ku di blokir selama nya.',
 'seru',
 'maen',
 'aplikasi ini de sangat sangat bagusss',
 'bagus buat denger arac songg',
 'bagus bngt rekomen sih cocok untuk liat video',
 'tolong dong apknya ios & os nya jangan di apain ini, tiktok ga support device gua minnn, kalo nonton bolak balik fore close, keluar keluar sendiri',
 'sangat baguss',
 'bagus',
 'aplikasi tik tok nya mantap . kita bisa belanja pakai tik tok shop dn bisa cari hiburan di tik tok.',
 'makasi tiktok',
 'apk bagus,',
 'ini sangat bagus',
 'gabisa update, beberapa efek ke kunci gabisa ke buka',
 'Mantul pokoe,bisa mengepresikan keejaan dan bisnis',
 'agus',
 'karna ndk bisa chat chtan',
 'fitur potongan harganya gak muncul',
 'saya tidak dapat mengatifkan aktivitas di tiktok tolong supaya bisa membuka aktivitas tiktok',
 'gak ada potong harga di HP oppo a19',
 'sebenernya seneng banget sm aplikasi tiktok,, tapi udh beberapa hari tiktok gak bisa buka komentar,, tidak ada jaringan internet terus,,, udh di hapus cache, data, uninstall, trus install lagi ttep. ga bsa buka komentar,, tiktok shopnya jg kaga ada,,, itukenapa yaaaaaaa.. klo dh bsa lagi sy kasih bintang 5',
 'bagus punya hiburan baru untuk aku',
 'jelek',
 'sangat baik',
 'sampai sekarang event potong harga 100 perak belum ada di akun ku padahal sudah ganti akun lebih dari 5× dan sudah di update',
 'lumayan bagus si banyak kekurangan nya tiktok',
 'seru lumayan',
 'bagus karena aku gak pake imel',
 'bagus dan cakep trimakasih sudah berikan tiktok aplikasi inii trimakasih banyakk ya 😍',
 'knp yhh di aku kdng suka macet" gitu. itu jaringan atau dri hp nya yh?🫠😤',
 'kebanyakan punya tiktok tapi gak di rating ,cihh kalo gak punya tiktok rasanya kayak kesepian',
 'suka keluar sendiri,gimana yah?!',
 'aplikasi membuat sakit hati',
 'aplikasi ini sangat seru',
 'ak suka baca berita di tiktok❤️ dan download lagu2 sech🎉kerenlah',
 'saya mendownload tik tok ini tidak bisa buat chat di Tik tok tolong perbaiki kesalahan ini makasih',
 'tiktok bgs,tp apa² kena pl trs pdhl mh ga ngapa² in',
 'adalah pokoknya',
 'bagus sih',
 'banyak iklan',
 'kenapa tiktok sekarang sering forclose sendiri',
 'apikk',
 'well',
 'kenapa yh aku ga bisa nge download lagi tiktok padahal aku butuh bngt buat belanja',
 'Saya jamin tiktoknya. bikin enak',
 'asik banget kalo nonton soalnya dapat film gratis tanpa internet tapi mines nya sering keluar dari aplikasihnya',
 'bug tidak bisa masuk ke aplikasi tolong di perbaiki',
 'lebih bagus lagi fiturnya',
 'tidak enak akun aku blokir terus',
 'akun aku sering kebelokir',
 'Ini tolong tik tok di perbaiki saya setiap buka tik tok sering kembali sendiri kadang tik tok sya jg gbisa di buka',
 'Tanpa basa basi',
 'bagus banget cok',
 'ga bisa dibuka aneh',
 'lagi scrol tiktok tiba tiba ke apus sendiri apl tik tok nya zzzz',
 'cukup 👍👍👍',
 'Aku instal ini karna youtube aku bleng',
 'Terbaik',
 'udh bagus bgt sih viturnya tpi bugnya anjir padahal aku pengen lihat live gwsm!',
 'Keren',
 'Bagus sekali Saya Akan Menggunakan aplikasi ini juga',
 'Aplikasi nya bagus banget',
 'coba deh bisa semua orang bisa liat video kita',
 "aneh, padahal jaringan baik' aja tapi lemot, vidionya si bisa di tonton tapi komen . . padahal buka apk lain aman' aja toh, udah 3 hari begini. udah di apus cache, hapus akun tetep aja tuh lemot",
 'bagus',
 'karna jelek',
 'ok',
 '𝕨𝕙𝕪 𝕝𝕠𝕒𝕕𝕚𝕟𝕘 𝕝𝕒𝕞𝕒 𝕓𝕒𝕟𝕘𝕖𝕥',
 'tiktok taaiii setiap mau liat produk kembali sendiri setiap mau cekout balik lagi GK bisa di buka eroro terus gila lama"tiktok fitur nya kek taiii',
 "lumayan lah ya,tpi suka nge bug tiba'",
 'knp abis di update ga bisa memposting ulang vd?',
 'baguss tapi kenapa tidak ada di layar beranda saya😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭',
 'apk nya sangat bagus klo bisa diupdate lagi trima kasih',
 'udh lama download tiktok tapi kenapa lihat komenan gabisa dan yg lainnya juga gabisa, bisa nya cuman scroll video doang aneh, katanya ga ada koneksi internet lah padahal saya punya paketan internet, tolong dong',
 'tik tok tidak bisa di instal katanya harus hapus aplikasi yang pas saya sudah hapus tidak bisa lagi.TOLONG DI PERBAIKI LAGI',
 'aku sih agak ada kecewa video aku gk fyppp itu aja sih',
 'tidak suka batasin umur ny.',
 'menarik tapi sedikit ngelag',
 'ngeleg tapi seru',
 'apply udah bagus banget',
 'saya sering buka tiktok tapi tidak bisa bikin akun',
 'Wih skrng jdi bgs fitur tiktok nya sesudah di update jadi mantap betull nih tiktok',
 'mantap',
 'Baguss bang',
 'tempat sarang monyet kepencet iklan langsung play store',
 'tidak bisa masuk ke tiktok',
 'Saya sudah lapor ke CS dan akun saya tetap di blokir tanpa penjelasan yang jelas, saya merasa tidak pernah melanggar peraturan dari tiktok tapi akun saya tetap di blokir, emang aneh ni aplikasi, easy bintang 1',
 'sangat asik',
 'kadang" apk nya tiba" lag sendiri padahal kalo buka apk lain aman aja',
 'please ini knp udh 100% dah ku tunggu tapi belum ke donwload',
 'tapi kenapa punya saya kayak agak lambat untuk fitur " baru ya gak ke apdute gitu kenapa ya',
 'See u',
 'sangat bagus carakerjanya meski bnyk iklan',
 'sekarang banyak iklan nya tt shop nya sampe berpengaruh ke apk lain',
 'mantap semakin ok dintiktok',
 'Apalah masak mau masuk tik tok keluar sendiri belum juga lihat video nya tiba² keluar sendiri tolong lah perbaiki bug seperti ini, masa mau lihat video tiba² keluar sendiri, sudah ngehabisi memori, keluar sendiri pula, 2 GB lebih loh apknya, perbaiki lah kek mana ini developer nya, terus kalau bisa setiap masuk toktok ini gak usah ada iklan bngst',
 'Kenapa di hp vivo y17s tidak ada fitur foto live di tiktok padahal di kamera hp ada fitur foto live😭',
 'kenapa tidak ada toko dan posting ulang pdhal sudah di update',
 'konslet',
 'kenapa tiktok hanya komentar dan pengaturan g bisa dibuka sudah 4 hari ..walaupun hanya scol² itu untuk belanja..tlng diperbaiki biar bisa belanja di tiktok',
 'dear admin, pengen bisa hastag banyak lagi',
 'kenapa ya saldo refund barang saya tidak bisa di ambil walau sudah tanggal 18. Mohon lah tiktok itu dana saya bukan dana anda, katanya ada pemeliharaan sistem, bohong mana ada pemeliharaan sistem selama ini.',
 'habis di update malah keluar" sendiri ga bisa di buka + GAUSA MENGADAKAN EVENT POTONG HARGA KALO POTONGAN NYA SAJA KECIL AND TIDAK MASUK AKAL',
 'tiktok bagus tapi gk bisa ngakunin tiktok nya',
 'ok',
 'kebanyakan di pencarian vidio negatif',
 'seru bangett ada tiktok pokoknya is debes👍🏻',
 'Krn KL mau pke kcpt Kya ad lmp ny jdi hrs hps and download ulg',
 'mantap',
 'aku punya akun yang bernama the king azzzam',
 'Bagus',
 'bagus,cuma saya ga bisa pesan streak',
 'ok',
 'mantap',
 'aplikasi nya ngecrash mulu tolong min diperbaiki lagi',
 'iklan mu menganggu di aplikasi lain',
 'Aplikasi nya bikin kesal,awal nya digunakan gak ada lelet2 tapi sekarang lelet nya minta ampun!!! padahal udh perbarui apk,gimana sih pihak tiktok😴😴. kalau masalah jringn gpplh ini indk jringn ok2 aja TPI apk nya ttp lelet!!!. semoga cepat diperbaiki...',
 'min kenapa tiktok shop ku hilang ya padahal umur udah sesuai, followers udah, update juga udah, tolong di tindak lanjuti ya 🙏🏻🙏🏻',
 'aplikasi ini sanggat bagus',
 'sering keluar sendiri gajelas bikin gamood, gatau kenapa habis di update mala makin gajelas apknya.',
 'aplikasi nya bagus, baik, dan nyaman digunakan, tetapi kurang suka sama respon nya, aplikasi ini banyak salah paham nya hanya karna membahas masalalu tentang SD malah terkena pembatasan usia. saya meminta untuk SEGERAH diproses tetapi responya kurang cepat💔',
 'i love tiktok',
 'Suka lag, keluar aplikasi sendiri, kadang gabisa dibuka sama sekali tolong diperbaiki ya',
 'gw gk bisa uninstall ni aplikasi njir, habis di uninstall pasti balik install lagi 😂 gitu terus',
 'min tolong tambahin fitur menonton video& dibayar dongg',
 'aplikasi yang sangat bermanfaat',
 'gak bisa di pake',
 'mantap',
 'kenapa ya,, setiap mau buka komentar selalu loading, pdhl kan sinyal bagus, soalnya buat main game pun lancar" aja',
 'bagus sekali',
 'bagus, tetapi suka sekali keluar keluar sendiri kenapa ya',
 'tiktok ini bagus banget untuk nonton drama pendek/dan juga bisa nonton dll',
 'ini mah apk paling saya suka sekali gak pelu di tnya kalau kekurangan nya apa sama kamu ???? pingin fypppp',
 'woi tiktok kenapa fitur kirim foto punya saya dihilangkan',
 'iklan yg mengganggu sekali',
 'kenapa gabisa buka komentar si? ga cuma komentar buka profil tiktok aja gabisa! loading Mulu pdhl wifi gk knp², udh di pakein paket data jga tetep gbsa',
 'bagusssss bngett plcccc',
 'aplikasi yang sangat populer di seluruh dunia🥰',
 'mantappp',
 'aku suka',
 'bagus',
 'apk ini sangat baguss',
 'tiktok nya bagus banget anjir',
 'makasih bgt tiktok saya makin suka dan seru 😀 semoga sukses selalu semuanya 🤲🏻 dan sehat selalu 😅',
 'tiktok ini sangat bagus karena ada banyak filem ada filem apa aja tapi aku mohon tiktok jangn bolk akun ku lagi ya',
 'keluar sendiri force close terus anjg',
 'apalah gw buka gak bisa akses internet padahal wifi nayala muncul notif tidak ada akses internet',
 'ini kenapa gak ada fitur toko nya weei',
 'ngehibur yg kesepian',
 'potong harga',
 'tolong play store tik tok ku kok ga bisa buat posting ulang ya jelek lgi gmna ya..',
 'apaaan cok lagi di apk lain lagi iklan tiba tiba banget masuk tiktok anjirrr ngeselin kali lah',
 'terblokir terus akun ku nabule',
 'yg aku udh updt taoi ko ga ada fitur shop nya',
 'tolong dong suka bgt keluar sndiri pdhl memo juga masih bnya, udh hps data berkali kali ttp gt aja, hrs didownload ulang baru bisa normal lagi, nanti seminggu lgi, blik ky gt lgi, muak bgt',
 'gak ada shop buat belanjanya',
 'tolong di perbaiki lagi sering banget ngebug pas makai apk ini padahal udh ada dari tahun bowo si raja tik tok, tapi makin ke sini makin parah dari masalah gaada jaringan pdhl udh pakai wifi udah beli kouta juga 100gb masih gabisa di pakai sampai aku uninstall ulang download lagi tetap gabisa kecewa bgt sama tiktok.',
 'Lo pengikut. Lo sudah 1k Kokok gak bisa live',
 'aplikasi yang bagus saya bisa menemukan berita apa saja disini aku kasih bintang lima',
 'bagus sekali',
 'apalah kocak tiktok kon..',
 'Good Application',
 'nge buflg terus perbaiki lah!MASA ADA PAMET SAMA DATA G BISA BUKA TIKTOK 30 MENIT',
 'aku posting video aku pake lagu yang aku mau. terus pas lama kelamaan lagunya keganti. maksudnya apa yah? mana lagunya jelek banget lagi kurang ajar',
 'sangat cocok 100',
 'semenjak di-update malah lemot dan tidak muncul pp,tidak tau mungkin hp yg ngeleg atau gimana, padahal sudah di refresh.',
 'anjirr lah banyak iklan',
 'ok',
 'bagus',
 'bagus tidak menyia menyiakan',
 'bagud banget bisa lihat Vidio yang bagus bagus',
 'bagus banget',
 'mantap',
 'terbaik',
 'banyak iklan',
 'dpt uang dr nonton dracin di tiktok',
 'mantap semoga saya bisa melihat info lengkap tentang istri yang baik dan benar dapat digunakan sebagai bahan hiburan 👍👍👍',
 'tiktok skrg baperan, dikit2 pelanggaran, padahal aplikasi ini sdh bagus, tapi jgn terlalu banyak pelanggaran',
 'belanja lebih mudah di tik-tok sambil scroll video pendek',
 'bagus',
 'minimal 0 pengikut udh bisa live lah',
 'tiktok nampilkan video seram-seram dimalam hari dan saya takut. rating 1 buat tiktok',
 'lumayan',
 'burik kg bisa isi link bio trus komen ilang',
 'everything is running smoothly after the update',
 'mantap',
 'bagus sangat menyenangkan',
 'Di beberapa perangkat hanya bisa mendownload tidak dapat mmenginstall dan selalu gagal mengistall, mohonnbantuannyanagar dapat mengunakan kembali',
 'cukup mendukung',
 'event 100 p, sumpah bikin orang cape',
 'JARINGAN FULL BUKA APK LAIN BISA LANCAR JAYA. GILIRAN BUKA TIKTOK GABISA. BENCI TIKTOK BOIKOT TIKTOK',
 'Mohon Maaf Min, Ini Semenjak Saya Update Tiktok Nya Agak Ngeleg Gitu Kalau Di Gunakan, Tolong Di Perbaiki Lagi Min 🙏🏻',
 'bagus',
 'kalo ga di urus aju banding yang kena pelanggaran pembatasan usia ga di urus napa ada program aju bandinh gua tanya?bilangnya 24jam kerja tapi sampe sekarang ga kerja" lu,kalo misalnya emang ga bisa aju banding ya jangan ada program aju banding kocakk',
 'ok',
 'ok',
 'ini aplikasi arah suka keluar sendiri,,,padah hp ram besar,,,MENDING DI HAPUS GK USAH DI DOWNLOAD',
 'jujur di saya ga ada masalah apa apa sama aplikasi dan fitur fiturnya, semua lancar bagus dan ga ada bug selama saya mendownload tiktok, tapi yang bikin saya malas membuka apk ini tuh makin banyak short drama barat yang terlalu seksual dan vulgar, yang saya heran kenapa sering sekali muncul di beranda saya, saya udah laporkan video tersebut sudah saya pilih opsi tidak tertarik tapi semakin lama semakin banyak dan semakin vulgar lagi video yang muncul, tolong dong di perhatikan kebijakannya',
 'fitur bagus bagus di aku gaada, giliran yang jelek aja banyak. kek potongan harga (Rp.100) aneh. pilih kasih ih',
 'bagus',
 'kenapa ya pas saya mau posting video kaga bisa di lihat orang lain tolong yak',
 'kenapa akun saya sering macet dari keluar sendiri, baru-baru ini kenapa akun saya tidak bisa ikut naik Komal dan tidak pernah dapat hadiah dari GB. tolong di perbaiki ya terima kasih',
 'apk tik tok suruh aku kaya',
 "aneh bgt akun gw yang satu tiba-tiba ilang yg satu tiba' rusak, gmna sih tik tok ini",
 'view dikit, banyak sering kena pelanggaran, itu knp, gak ngapa2in kena pl... aneh, di perbaiki lah...',
 'knapa setiap kluar apl mau masuk lgi GK bisa,,tolong di perbaiki',
 'aplikasi ini sangat berguna dan membantu,tapi kenapa kok sering ada yg kurang jelas di peraturan" nya,apa saya yg gagal faham ya,tau ah.pokoknya mantap,terima kasih',
 'ga bisa di main',
 'TAMBAHKAN FITUR NYIMPEN FOTO DI CHAT TIKTOK MIN',
 'boleh boleh gayanya ini',
 'bagus',
 'kenapa akun tiktok saya sekarang tidak bisa menggunakan tiktok shop padahal saya tidak pernah melanggar aturan dan alasan nya karena usia padahal usia saya udah lewat dari 18 tahun',
 'TOLONG DONG ADAIN PIN CHAT LAGI😭🙏🏻',
 'penghibur yg setia🤩🤩🤩🤩🤩',
 'puwenak ngilang i gsbut',
 'bagus sih cuman sekarang ada kesalahan gatau kenapa padahal wifinya ga ngelag gabisa nengok komen dan video private',
 'pokonyh mantap',
 'template hilang musik nya juga berkurang punya ku doang apa yang lain juga?',
 'Sangat bagus dan bermanfaat',
 'kasih filtur privasi setatus yang bisa memilih 1 akun atau lebih, jgn filtur privasi yang hanya teman yang bisa melihat',
 'ni aplikasi bagus tapi tolong lah kalau nge kompres video jangan terlalu banyak dari yang awalnya hd 2K 60fps jadi 480p 30fps itu udah parah banget buriknya, alhasil jadi gak mood mau bikin konten lagi',
 'mohon diperbaiki karna sering keluar tiba2 ketika sedang live🙏🙏🙏',
 'bagus',
 'setelah update ko stiap nonton vidio selalu ngelag. dikira jaringan wifi gua gangguan. tpi baca komen dll bisa. vidionya aja ngelag. soalnya bukan skali 2x. stiap lgi scroll dan ada vidio yg kita tonton kadang ngelag !',
 'baguss buatt hiburan sayaaa biarr engakk bosenn dann buatt galau jugaa bisaaa',
 'apk sangat bgus tpi knp akunku pay latter nya g bs d buka kemarin masalah ny aq salah ketik dana juga gk balik mu bayar gak bs tolong saya',
 'ok',
 'Bisa"nya iklan Judi Online bisa masuk apk tetrend gini masih bisa dirayu iklan slot judi online',
 'sangat bagus untuk orang berapresiasi dan berkreasi dengan fitur fitur yang sangat membantu dan bisa menghasilkan uang jutaan rupiah. semogah ke depan nya lebih baik lagi dan bisa jadi no satu aplikasi penghasilan uang.',
 'mudah digunakan',
 'tiktok 2026 makin gak jelas, jualan nampilkan barang masih aja kena pl,dan pnonton jdi sepi klo sdah kna pl',
 'bagussss',
 'aplikasi isinya 99% iklan',
 'bagus',
 'sering kena batas usia gk bisa di buat DM tolong dong tiktok',
 'makin lama makin engga jelas akun udh masuk terus keluar lgiii hadeuh lama"gua beli nih tiktok',
 'luar biasa',
 "jadi ga bisa Download apk nya sebelum nya bisa,tapi ini tiba' gabisa",
 'sedih bgt gabisa kirim pesan dan nerima pesan karna batasan usia padahal gasengaja nyebut umur yang cuman bercanda aja tadinya',
 'aplikasi nya sdh bagus tpi makin lama makin lelet di pakai',
 'aplikasi nya mohon diperbaiki lagi banyak bug kadang macet ngecrash parah sangat berat',
 'mantep 👍👍',
 'sangat untung',
 'Good app. Bisa dapatkan penghasilan dari aplikasi ini.',
 'minn kok tiktok shop aku gada koin potongan harga',
 'sangat bagus',
 'nice',
 'saya kasih bintang satu karena akun saya tiba-tiba kena ban permanen, padahal saya tidak melakukan apa-apa',
 'ya, ok, bagus',
 'okeee',
 'belanja di tiktok shop lama banget pengirimannya, kurir di chat sok ngartis, berkali-kali laporan tetap aja lama progresnya, pesanan gak diantar antar, csnya juga jawabannya template, statusnya udah diterima tapi barangnya gak sampai',
 'kenapa pembagian fiturnya gak adil?!',
 'kre and mantap',
 'aplikasinya bgus',
 'sangat menyenangkan bagi saya bisa mengisi waktu luang dengan video bermanfaat dan juga bisa dipakai untuk berbisnis pokonya sangat bagus , good joob🤩👍👍',
 'oi, kalo buat apk jangan banyak peraturan nya lah, masa dikit" kena pelanggaran, padahal gua ga ngomong kasar dan dll, mana streak gw dah banyak, gabisa ngirim pesan, aduhhh payah',
 '🤗🤗',
 'knpa tiktok ga bisa liat tmn sedang live di kontak masuk notifikasi',
 'BARESKRIM MABES POLRI.. TIKTOK SEKARANG KERJASAMA DENGAN SITUS JUDOL !!! MOHON DIPROSES JUDOL DI TIKTOK !!! IKLAN ISINYA JUDOL SEMUA DITIKTOK..',
 '👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍',
 'gatau akhir akhir ini suka keluar sendiri dari aplikasinya',
 'selalu ngelag dan tidak menanggapi',

In [6]:
%%time
model = ITER_DBSCAN(initial_distance=0.4, initial_minimum_samples=16, delta_distance=0.01, delta_minimum_samples=1, max_iteration=15, algorithm="IndoBERT", metric="euclidean")

CPU times: user 15 μs, sys: 1e+03 ns, total: 16 μs
Wall time: 21 μs

In [7]:
%%time
labels = model.fit_predict(dataset)

Loading HuggingFace model...
Model Loaded.

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

CPU times: user 2min 33s, sys: 4.68 s, total: 2min 38s
Wall time: 42.8 s

In [8]:
df['cluster_ids'] = labels
df.cluster_ids.value_counts()

cluster_ids
-1     864
 1      42
 0      22
 2      19
 3       8
 4       8
 5       7
 6       6
 9       4
 7       4
 8       4
 10      3
 11      3
 12      3
 13      3
Name: count, dtype: int64

In [9]:
df.to_excel("result.xlsx", index=False)

In [10]:
evaluate_dataset = EvaluateDataset(filename=filepath, filetype='csv', text_column='content', 
                                   target_column='intent')

In [11]:
parameters = [
             {
    "distance": 0.4,           # Ditingkatkan agar cakupan lebih luas
    "minimum_samples":16, 
    "delta_distance":0.01, 
    "delta_minimum_samples":1, 
    "max_iteration":15,
    "algorithm": "IndoBERT",
    "metric": "euclidean"
},
{
    "distance": 0.4,           # Ditingkatkan agar cakupan lebih luas
    "minimum_samples":16, 
    "delta_distance":0.01, 
    "delta_minimum_samples":1, 
    "max_iteration":15,
    # "algorithm": "IndoBERT",
    # "metric": "euclidean"
}]

In [12]:
%%time
results = evaluate_dataset.evaulate_iter_dbscan(parameters)

Loading Tensorflow model....
Model Loaded.

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
100%|██████████| 2/2 [00:02<00:00,  1.24s/it]

CPU times: user 16.3 s, sys: 4.31 s, total: 20.7 s
Wall time: 13.8 s

In [13]:
result_df = pd.DataFrame.from_dict(results)
result_df

,distance,minimum_samples,delta_distance,delta_minimum_samples,max_iteration,algorithm,metric,time,percentage_labelled,clusters,...,homogeneity_score,completeness_score,normalized_mutual_info_score,adjusted_mutual_info_score,adjusted_rand_score,accuracy,precision,recall,f1,intents
0,0.4,16,0.01,1,15,IndoBERT,euclidean,1.35,13.3,14,...,0.05,0.24,0.08,0.07,-0.02,0.321,34.4,32.1,21.7,3
1,0.4,16,0.01,1,15,NaN,NaN,0.87,5.6,4,...,0.01,0.08,0.03,0.02,-0.01,0.242,12.7,24.2,13.7,2

In [14]:
result_df.to_csv("result_evaluation.csv", index=False)